//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileVersion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FileVersion()
        {
            this.Files = new HashSet<File>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FileID { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
        public Nullable<double> Number { get; set; }
        public System.DateTime DateCreatedSys { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int AuthorID { get; set; }
        public string FileTypeName { get; set; }
        public int FileContentID { get; set; }
    
        public virtual EmployeeRole EmployeeRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<File> Files { get; set; }
        public virtual File File { get; set; }
        public virtual FileContent FileContent { get; set; }
        public virtual FileType FileType { get; set; }
    }
}
