//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilesScope
    {
        public string Level { get; set; }
        public int RoleID { get; set; }
        public string Permission { get; set; }
    
        public virtual FileLevel FileLevel { get; set; }
        public virtual FilePermission FilePermission { get; set; }
        public virtual Role Role { get; set; }
    }
}
