//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public File()
        {
            this.Bookmarks = new HashSet<Bookmark>();
            this.FileActionLogs = new HashSet<FileActionLog>();
            this.FileMentions = new HashSet<FileMention>();
            this.FileVersions = new HashSet<FileVersion>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public System.DateTime DateCreatedSys { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int AuthorID { get; set; }
        public Nullable<int> CurrentVersion { get; set; }
        public bool Active { get; set; }
        public bool Locked { get; set; }
        public Nullable<System.DateTime> LockedUntil { get; set; }
        public int LevelID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookmark> Bookmarks { get; set; }
        public virtual EmployeeRole EmployeeRole { get; set; }
        public virtual FileVersion FileVersion { get; set; }
        public virtual FileLevel FileLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileActionLog> FileActionLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileMention> FileMentions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileVersion> FileVersions { get; set; }
    }
}
