//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstitutionActionLog
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public int InstitutionID { get; set; }
        public System.DateTime ActionDate { get; set; }
        public string PermissionName { get; set; }
    
        public virtual EmployeeRole EmployeeRole { get; set; }
        public virtual Institution Institution { get; set; }
        public virtual InstitutionPermission InstitutionPermission { get; set; }
    }
}
