//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int ID { get; set; }
        public int SenderID { get; set; }
        public int RecieverID { get; set; }
        public int FileContentID { get; set; }
        public string FileTypeName { get; set; }
        public string Text { get; set; }
        public string HeaderText { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool Seen { get; set; }
        public bool DeletedFromSender { get; set; }
        public bool DeletedFromReciever { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual FileContent FileContent { get; set; }
        public virtual FileType FileType { get; set; }
    }
}
